### ISSUE TITLE
Stories Shortcode

### ISSUE THREAD

**Issue by samvthom16** [akvo/Akvo-Theme#17]
Create a stories shortcode that would pull the stories in this format here: https://designbychris.co.uk/akvo/newsite/europe.php

**Comment by designbychris** [comment]
Have added this in and updated the shortcodes.php file

**Comment by designbychris** [comment]
I have also added in the nested filter shortcode and updated the shortcodes.php file.

**Comment by samvthom16** [comment]
Improvement from Linda: On the partners page, can you set the cursor so it only changes from arrow to hand symbol if there is a link added to the logo?

**Comment by designbychris** [comment]
@samvthom16 I think that for this, we may need to have a field in the CPT for Partners to allow a URL to be added, as currently there isn't an option to add a link to the logo.

Can you add this field, and if its added then allow the link to be added to that logo within the grid on the Partners page loop.
