### ISSUE TITLE
Microstory Additional Widgets

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#189]
Hi @samvthom16 we have some extra widgets we need building for the new Microstory Page. I'm going to suggest that the team use the builder to rebuild the microstories (you may have seen this in Skype), can you build the following ones (i've added them into the /lib/templates folder in GitHub), for both examples please go to https://designbychris.co.uk/akvo/newsite/microstories.php to show the examples below:

**akvo_iframe_report.php** 
this is a widget for the iFrame with a title as shown on my example pages above. It is about half way down. I think that this is just a case of having a field for the title and a field for the iFrame content. The rest should just remain the same I think :)

**akvo_statistics.php**
This is for the second section on the Microstory page. It is a flex block unit that should allow for multiple columns, they should allow for both images and text with links. This might be best as just some sort of repeater function (like in ACF), the icons will need to be selectable from the set of Font Awesome Pro ones. I believe that you have had this request already from Linda.

I hope that this all makes sense?

**Comment by samvthom16** [comment]
@designbychris Have you tested them locally? These were completed last week.

**Comment by designbychris** [comment]
I will test these again now.

**Comment by designbychris** [comment]
Statistics working perfectly :)
