### ISSUE TITLE
Additional Widgets for Product page

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#201]
Hi @samvthom16 here are a list of extra widgets needing to be made. I have added in the PHP into the /lib/templates folder for you.

akvo_process.php - this is for the Product page it looks like the circle boxes on this static page here: http://designbychris.co.uk/akvo/newsite/water-quality.php if you scroll down you will see a block of 6 icons in circles. Ideally we will have the ability to add new items, and it will flex to grow and reduce accordingly. I believe that I have already coded for this in mind style wise. Linda would like the ability to change out the FontAwesome icon for one of their own design, so this functionality will need to be added in.

There will be an updated pricing table widget (its called Price Box (PB) in the builder) that will need to be built, which will essentially work in the same way as the current one. If we can amend the current one with some removal of bits and change the style then that would be ideal. Let me know.

**Comment by samvthom16** [comment]
@designbychris I have added the widget for akvo process icons but I still see the responsive issues and the button does not get active on click. There is some gap in the UX from what we have here: http://designbychris.co.uk/akvo/newsite/water-quality.php. Can you please look into this?

**Comment by samvthom16** [comment]
@designbychris All the widgets in the SiteOrigin Page builder don't have any documentation as such to hack them from our theme. Either we use the widget as it is and override the styles from our css. Or we make a completely new widget.

**Comment by designbychris** [comment]
We may need to build a new pricing widget then... I will work on a new design for one.. it should hopefully be a pretty simple one :) thanks for the update. I will look at the process icons issue

**Comment by designbychris** [comment]
@samvthom16 I can't see the Akvo Process in the list of active widgets within the SO Widgets. Can you sort this so that I can test it properly on the stage?

**Comment by designbychris** [comment]
@samvthom16 the Akvo process is working, apart from the bit of code to make the button have a class of btn-info when its clicked, I can see the code you're using is: 

<?php if( $i ){ _e('btn-default'); } else{ _e('btn-info'); }?>

Its just not changing over to btn-info when active, and being btn-default when inactive. If you can fix that then we should be good for this widget :) as my responsive CSS is working a treat :)

**Comment by designbychris** [comment]
bugger, I thought that I had included that... i'm sorry .. bare with me

**Comment by designbychris** [comment]
So so sorry :( I forgot to include this js file
[process.zip](https://github.com/akvo/Akvo-Theme/files/2628690/process.zip)
I have zipped it up.. but if you extract it and add the .js file to be used for this process then it should work :) 

Sorry again :( utterly my fault.

**Comment by samvthom16** [comment]
@designbychris can we close this?

**Comment by designbychris** [comment]
Yes :) sorry
