### ISSUE TITLE
Hide Places of Interest on Google Maps

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#212]
Hi Sam, 

Can you add the correct code to hide all places of interest from the Google Maps in the builder :)

https://developers.google.com/maps/documentation/javascript/examples/hiding-features 

Just in case you need any reference :)

Chris

**Comment by samvthom16** [comment]
@designbychris All the widgets in the SiteOrigin Page builder don't have any documentation as such to hack them from our theme. Either we use the widget as it is and override the styles from our css. Or we make a completely new widget.

This is the only documentation I have found for the map widget: https://siteorigin.com/widgets-bundle/google-maps-widget/. If this doesn't help, then we will have to discuss the alternatives.

**Comment by designbychris** [comment]
Hi mate, its ok. I found the solution for the map :) as it allows Snazzy Maps JSON which I used and it looks great :)
