### ISSUE TITLE
Accordion fixes

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#215]
Hi Sam,

Can you look at the accordion issue below:

When you open an accordion item, then if you scroll to open the next one down, it doesn't jump back up to the top of the accordion item that you have just opened. If you look at https://staging3.akvo.org/terms-and-conditions/ and try opening a few of them, you should see what I mean. If you get stuck, please ask Linda for a screenshare to explain :)

**Comment by samvthom16** [comment]
@designbychris All the widgets in the SiteOrigin Page builder don't have any documentation as such to hack them from our theme. Sorry don't have much on this to make it better as this is not style issue.

**Comment by designbychris** [comment]
Blast... we are going to need to find out why/how to make it not jump if at all possible.. Or we're going to have to make a new accordion widget to allow us to control how the open/close function works

**Comment by designbychris** [comment]
Might need to investigate a way to achieve this.. as its a bit buggy on the open close of the accordions.

**Comment by Lindaleunissen** [comment]
I will hold off on populating these any further until we've got this figured out, as it is quite a lot of work to do.

**Comment by designbychris** [comment]
I wonder if something like this might help @samvthom16 https://github.com/siteorigin/so-widgets-bundle/issues/785

As this says something about using anchor tags for when the accordions are pressed.

The alternative is that we build a new set of accordions and use them instead? What are your thoughts Sam?

**Comment by designbychris** [comment]
@samvthom16 I have put some code in the /lib/ folder called akvo_accordion.php it uses the same code shown here: https://designbychris.co.uk/akvo/newsite/jobs.php with the accordion. Can you try making that into an available widget, to see if that fixes the problem?

**Comment by samvthom16** [comment]
@designbychris yes we can try the new one

**Comment by samvthom16** [comment]
@designbychris Please test the accordion on staging

**Comment by designbychris** [comment]
Will do :)

**Comment by designbychris** [comment]
@Lindaleunissen I have mocked up a few on the duplicated version of the Terms & Conditions page ( https://staging3.akvo.org/?page_id=47176&preview=true ) can you have a look and see if that improves things?

**Comment by Lindaleunissen** [comment]
It's looking good. We've lost the option to just open 1 panel at a time though, which I quite like. @samvthom16 Is it possible to add that back in?

I'd prefer a different icon to indicate that it's a accordion. I assume the down arrow is from FontAwesome? Can we use _far fa-chevron-down_ instead?

Thank you!

**Comment by designbychris** [comment]
@Lindaleunissen I have sorted this and added the chevron-down for you now. Please take a look :)

**Comment by Lindaleunissen** [comment]
Looks Lovely. Thanks @designbychris 
@samvthom16 Do you think it would be possible to have just one panel open at a time?

**Comment by samvthom16** [comment]
@designbychris What is your take on opening one panel at a time? And any ideas on how to do it? Also don't want to run into the same issues with the site origin accordion.

**Comment by designbychris** [comment]
@samvthom16 not sure if its possible unfortunately.. i'm still looking into it.. but we might not be able to do this very easily.

**Comment by samvthom16** [comment]
@Lindaleunissen keeping one panel open at a time would cause the same issue like the other accordion. I'm suggesting that we use this one for lengthy content and the other site origin for shorter content.

**Comment by Lynngre** [comment]
https://github.com/siteorigin/so-widgets-bundle . The widgets are all open source code, if that helps.

**Comment by samvthom16** [comment]
@designbychris I was giving this one more shot. Is custom JS being used for this one or the bootstrap one?

**Comment by designbychris** [comment]
I think that it was the bootstrap one.. but there might be some JS being used within my custom JS file (the akvo_scripts.js) I can't remember off the top of my head tbh.

**Comment by designbychris** [comment]
Closing thread for the timebeing, re-open it if needed.
