### ISSUE TITLE
Microstory Hero Text

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#222]
Hi @samvthom16 can you add an option to the microstories to allow the admin to remove the title text from the microstory hero area? Like we have on the pages etc. We want to retain the image, just the option to hide the text.

**Comment by samvthom16** [comment]
@designbychris I don't think we should add this in the page settings as we will end up bloating the same considering all use cases.

**Comment by designbychris** [comment]
Hmm thats odd.. can you set it for the Microstories, Linda will need to change the Pages to be a Widget instead to show the image.

**Comment by samvthom16** [comment]
@designbychris I'm a bit confused here. I checked the code for single-microstory, and the title with the image has been hardcoded. So you want the option to hide the title only and not entire section like we have on pages?

**Comment by designbychris** [comment]
Yes please, just want the option to hide the title like on the pages. But we want to keep the Hero image, just to hide the text if a tick box is ticked.

**Comment by designbychris** [comment]
https://staging3.akvo.org/stories/americas/test-microstory/ on this one.. for example, if I ticked the box. The Hero image (which is the featured image) would remain but the text Test Microstory, would be hidden :)

**Comment by samvthom16** [comment]
@designbychris then there would be no uniformity among the settings, also it doesn't apply to the case if the whole image section needs to be removed in the future for something else.

**Comment by designbychris** [comment]
okie dokie :)
