### ISSUE TITLE
Microstory page widget amends

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#224]
Hi @samvthom16 here are some widget amends that I need you to look at on the Microstory pages:

the iFrame report widget, currently this widget is wider than the text below, as its within a container for the .so-widget-sow-editor giving it some additional padding around the text. Can we add this to the iFrame Widget as standard so that it doesn't look wider than the rest of the text.

Same goes for the image container.  I'm using the SiteOrigin Image display, but its making it full width of the container. Can we build an Akvo single Image Widget that sticks and image within the same container as the SiteOrigin text editor, so that it stays inline with the text etc.
 
If you look at: https://staging3.akvo.org/stories/americas/test-microstory/ this shows both issues.

**Comment by samvthom16** [comment]
@designbychris I don't think we should be creating a new widget for these. These can be aligned by overriding the styles. For the tinymce, following are the styles that are added (do note this was copied from the previous design):

`body.single-microstory .so-widget-sow-editor, body.single-microstory .narrow-row{
max-width: 1000px;
margin-left: auto;
margin-right: auto;
padding: 50px 20px;
box-sizing: border-box;
}`

**Comment by samvthom16** [comment]
@designbychris have you worked this out?

**Comment by designbychris** [comment]
Works perfectly :) thanks. Is there a way to add a drop down option somewhere in the design options on the row, to dynamically add this class? I can just see that some of the normal admins might struggle to remember to add this class.

**Comment by samvthom16** [comment]
Nope. We can add this to the Readme file for docs.

**Comment by designbychris** [comment]
ok
