### ISSUE TITLE
Header image widget height

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#228]
At the moment I can use the "akvo slider" widget to set the height of the header image to 'default' or 'narrow'. We need a third height - let's call it 'extra narrow'. See image below for approximate height.

From left to right, heights are Default, Narrow, Extra Narrow
<img width="1630" alt="screen shot 2018-11-29 at 15 24 30" src="https://user-images.githubusercontent.com/5338081/49232011-13cf0a80-f3eb-11e8-937d-5ef020ce8fd6.png">

**Comment by samvthom16** [comment]
@designbychris What would the height be in pixels?

**Comment by designbychris** [comment]
@samvthom16 I have asked Linda to let you know pixel height :)

**Comment by Lindaleunissen** [comment]
I don't know the pixel height of the other 2 sizes, so I don't know how to tell how many pixels that is. That's why I took screenshots. I'd like the same distance in pixels above the text as underneath it. Does that help? 
@designbychris @samvthom16

**Comment by designbychris** [comment]
I will see if I can sort this out for you @samvthom16, bare with me

**Comment by designbychris** [comment]
@samvthom16 heights as follows please:

Default - 620px high (this should already be set to this high I believe)
Narrow - 450px high (this should already be set to this high I believe)
Extra Narrow - 250px high

**Comment by samvthom16** [comment]
@Lindaleunissen @designbychris  I have pushed the code. Could you confirm if this works?

**Comment by samvthom16** [comment]
https://github.com/akvo/Akvo-Theme/issues/53

**Comment by Lindaleunissen** [comment]
Works and looks fab. Thank you!
