### ISSUE TITLE
Site issues

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#243]
Hi Sam,

Can you look at a couple of issues:

1. On the Statistics widget - the Font Awesome Pro integration.
2. On text editors, can you allow the <br/> to be able to be used or for the system to allow for hard returns.

Please check with Linda about the above :)

Thanks

Chris

**Comment by Lindaleunissen** [comment]
Hi Sam. 
1 I've added fontawesome code to the statistics section. But it doesn't show in all cases. 
2 This was mainly for adding empty 'spacing' lines. Normal hard returns work fine, but with the padding amends that Chris has made, this is not really an issue anymore. 

Thanks, L

**Comment by samvthom16** [comment]
@Lindaleunissen I would need to what exactly are those icons which are not showing. Please list a couple of them for me to test.

**Comment by Lindaleunissen** [comment]
It only shows the icons that are available in the 'select icon' option. Anything that I type in the Font awesome pro icon box that is not in the 'select icon' option doesn't work. 

I've tried entering the code in different ways, but none work:
1) <i class="far fa-handshake-alt"></i>
2) fa-handshake-alt
3) far fa-handshake-alt

If you look at the master microstory, I have uploaded 5 different icons in the 'partnership details' section and none are showing. 

When I put fa-leaf in, it did show, but none of the pro icons appeared, the one that appeared was the one that was available in the 'select icon' box, which is not the same as on fontawesome.com

**Comment by samvthom16** [comment]
@Lindaleunissen please share the backend link of the master microstory template

**Comment by Lindaleunissen** [comment]
Code above at 1 disappeared:
< i class="far fa-handshake-alt"> </i>


Also here a list of the icons in the partnership details section:
far fa-handshake-alt
far fa-globe-americas
far fa-hand-holding-seedling
fal fa-person-dolly
far fa-hammer

**Comment by Lindaleunissen** [comment]
back end link:
https://staging3.akvo.org/wp-admin/post.php?post=45388&action=edit&lang=en

**Comment by samvthom16** [comment]
@Lindaleunissen it seems that fontawesome has upgraded their API. I'm changing the way the icons are displayed, so you might have issues with the old ones that are already entered in the system.

**Comment by Lindaleunissen** [comment]
Ok, thanks. 
Looping @designbychris into this thread, as he embedded fontawesome icons on several pages in the website.

**Comment by samvthom16** [comment]
@Lindaleunissen @designbychris This will only affect the icons used in Stats and Process widgets. You can find the pro icons working here: https://staging3.akvo.org/stories/akvo-hub/test-microstory/

**Comment by Lindaleunissen** [comment]
hooray! Thank you!
