### ISSUE TITLE
Equal height boxes in same row 

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#256]
Hi Sam, 

Can you set the builder so that we can make boxes equal in height? 
I have 2 boxes next to each other on the homepage, and ideally they'd be the same height. See screengrab below. 

Thanks!
<img width="1175" alt="screen shot 2018-12-05 at 11 09 34" src="https://user-images.githubusercontent.com/5338081/49509797-4ad76d00-f87e-11e8-91a2-ef4eacc85b6c.png">

**Comment by Lindaleunissen** [comment]
I found a similar image on [this page](https://staging3.akvo.org/capture-and-monitor-data-at-scale/): where I'd like the buttons to all sit at the same level. 
<img width="1233" alt="screen shot 2018-12-05 at 14 18 47" src="https://user-images.githubusercontent.com/5338081/49519432-db22ab80-f898-11e8-86cd-f0ca131b8f67.png">

**Comment by designbychris** [comment]
@samvthom16 Also on this.. can you look here: https://staging3.akvo.org/capture-and-monitor-data-at-scale/

Can we make it so that we can set the image to be in line with the content?

**Comment by samvthom16** [comment]
https://siteorigin.com/thread/equal-height-of-the-content-in-rows-columns/

**Comment by samvthom16** [comment]
@designbychris I suggest that you use a css class if padding or margin settings don't work.

**Comment by Lindaleunissen** [comment]
Perfect. Thank you!

**Comment by samvthom16** [comment]
The class has been updated to `eq-col` because of a conflict with flex boxes https://github.com/akvo/Akvo-Theme/issues/280

**Comment by designbychris** [comment]
This all seems to be working perfectly :) @Lindaleunissen can you check too :)
