### ISSUE TITLE
Titles for tabs/accordions in back end

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#257]
Hi Sam

In the microstories section (Master microstory) we have a section in the builder called "Partnership details" (originally called metrics). In here we add partner names, location, etc. It would be good if those titles would be visible in the widget (at the moment it just states 'item'), as it would speed up content population quite a lot. I can already do this on the accordion widget.

<img width="557" alt="screen shot 2018-12-05 at 11 10 35" src="https://user-images.githubusercontent.com/5338081/49509893-91c56280-f87e-11e8-8ee1-8967410e2c90.png">

**Comment by samvthom16** [comment]
@Lindaleunissen I need more clarity on this.

**Comment by Lindaleunissen** [comment]
On the accordion widget I can change the title of the panels in the backend - see screen grab below. 
Alvaro requested the metrics widget to be set up in the same way, as it will make content population easier if we can see right away what each item is. 

<img width="918" alt="screen shot 2018-12-06 at 10 11 51" src="https://user-images.githubusercontent.com/5338081/49577636-bf261500-f93f-11e8-82ff-08d9c6121555.png">

**Comment by samvthom16** [comment]
@Lindaleunissen I have updated on staging. Please confirm if this works or needs more updates.

**Comment by Lindaleunissen** [comment]
Perfect! Thank you!
