### ISSUE TITLE
Statistics widget

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#259]
I've copied the statistics widget onto the microstory pages, however, there are a few bugs in it. 

1 When using less then the standard number of items the columns are not centred. 
2 Even though the text is set to white in the design side panel, not all text is actually displaying as white. This has happened on other occassions too. @designbychris can elaborate if needed. 

<img width="1388" alt="screen shot 2018-12-05 at 14 48 47" src="https://user-images.githubusercontent.com/5338081/49521471-6867ff00-f89d-11e8-9af0-911af409b717.png">

**Comment by samvthom16** [comment]
https://github.com/akvo/Akvo-Theme/issues/189

**Comment by designbychris** [comment]
I think it was just that the color wasn't set to inherit. which I have fixed.. I think. I will however double check this.

**Comment by designbychris** [comment]
I have fixed this.

**Comment by designbychris** [comment]
I can see the problem.. its a flex issue
