### ISSUE TITLE
Tweetbox widget

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#279]
Hi Sam,

One more Widget to build for the builder (and hopefully a shortcode too, just so that it can be used out of the builder).

I have created the template within the lib/ folder. Its called akvo_tweet.php.

The idea is, that the admin can set up a tweet which will be within the main content, then the link will send you to twitter to tweet that text and a link to the post itself.

Hopefully pretty straightforward. There will no doubt be some styling that I will need to do when its done, if you could just set it up so that I can set a test version to finish / fix styling, that would be great :)

Ta

Chris

**Comment by samvthom16** [comment]
@designbychris do we have a link that already has this work done? I just wanted to see for visual reference.

**Comment by designbychris** [comment]
@samvthom16 yes of course, please go here: https://designbychris.co.uk/akvo/newsite/single3.php about halfway down it should have the click to tweet section. The only difference will be that the colours need to be selectable by the admin. So if they want the box green and the text white, they can. I can sort the CSS afterwards, I think. We just need to have it ready for that functionality :)  does that help?

**Comment by samvthom16** [comment]
@designbychris Please test the tweetbox on staging

**Comment by designbychris** [comment]
Will do :)

**Comment by designbychris** [comment]
Works perfectly :)
