### ISSUE TITLE
Flex box issue

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#280]
Hi @samvthom16 ,

Not sure what the issue is here.. So i'm hoping that you can take a look and see if its something that needs debugging:

https://staging3.akvo.org/stories/east-africa/addressing-shared-water-risk-in-tanzania-with-iwasp/

On this page, i've added a second row for the statistics bit in the page. But for some reason its kept the same height as the row above, even though on the page its in 2 separate rows in the builder and within 2 separate widgets.

Could you do a check on the code, as they seem to all be the same height as the tall one.

Chris

**Comment by designbychris** [comment]
hmmm ok... but that still doesn't explain why its on 2 separate elements why the .col is taking the equal heights from the section above... Is it getting them from ALL the .cols on a page and making them ALL the same size?

**Comment by samvthom16** [comment]
Yes I'm afraid so. I'll have to use a different class and then check if the issue has been resolved. Will finish this by thursday.

**Comment by designbychris** [comment]
Cool :) thank matey :D

**Comment by designbychris** [comment]
the .col issue seems to have gone to here too : https://staging3.akvo.org/blog/ they are all really tall when they should be flex height.

Is this something that will be fixed by your other class fix?

**Comment by samvthom16** [comment]
@designbychris 
I'm not using the `.col` class anymore so this conflict should be resolved. Can you confirm?

**Comment by designbychris** [comment]
will check now :)
