### ISSUE TITLE
narrow-row CSS doesn't work on full width row

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#283]
On image rows in the microstories I add narrow-row to the CSS to get them to display at the right width, which works fine on a standard width row. 

If I however want to set the bg colour to a different colour, eg. grey, I have to set the row to full width, which results in the image aligning to the far left of the page.

I've recreated the issue on the page below, first image is on a full-width row, second one on standard width. 

https://staging3.akvo.org/stories/europe/monitoring-the-salinity-of-surface-water-in-the-netherlands-with-acacia/

Thanks!

**Comment by samvthom16** [comment]
@Lindaleunissen For the use of class `narrow-row` within a fullwidth row, you will have to use a nested layout builder. I have done this for this page: https://staging3.akvo.org/stories/europe/monitoring-the-salinity-of-surface-water-in-the-netherlands-with-acacia/

**Comment by Lindaleunissen** [comment]
Yes, that works, thanks!

**Comment by designbychris** [comment]
Can this be issue closed @Lindaleunissen ?

**Comment by Lindaleunissen** [comment]
If there is a way of getting it to work without a nested builder, that would be preferential. 
It's just another not-so-straightforward thing to explain to other team members.

**Comment by samvthom16** [comment]
@Lindaleunissen No that won't be possible.
