### ISSUE TITLE
Carousel text

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#288]
Since we have a limited amount of good quality images, I'm thinking maybe in some cases the carousel could work slightly differently. [Take this page for example](https://staging3.akvo.org/capture-and-monitor-data-at-scale/): would it be possible to keep the image static, and only have the text rotate?

@designbychris @samvthom16

**Comment by designbychris** [comment]
I have made the slider fade between slides instead of doing the slide from left process. I think that this improves it :) what  do you think @Lindaleunissen  :)

**Comment by samvthom16** [comment]
@Lindaleunissen @designbychris  can we close this? Or is there anything pending?

**Comment by designbychris** [comment]
I think that this can be closed unless @Lindaleunissen has any objections :)

**Comment by designbychris** [comment]
This is being closed, @Lindaleunissen can reopen it if she needs to
