### ISSUE TITLE
Icon Widget

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#289]
Hi Sam,
Can you create a widget which will just display a FontAwesome Pro icon and allow you to set the colour, font size and if its centered, align left or align right.

Ta :)

**Comment by designbychris** [comment]
@samvthom16 I have set this for you into the lib/templates/

**Comment by samvthom16** [comment]
@designbychris You can start testing this out

**Comment by designbychris** [comment]
It looks good to me :) thanks @samvthom16
