### ISSUE TITLE
Amendment to Akvo Custom Posts Widget

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#298]
@samvthom16 can you add the functionality to allow someone to select specific posts from within a post type, not just by filtering by taxonomy, but like from a search function, based on the number of total items. If its over 6 items don't allow this functionality, but under 6 items, allow the admin to select which posts to display?

**Comment by samuelpyramidions** [comment]
@designbychris I need more context. What's the problem that we are solving here? 

Also just to let you know that there is a certain limit to the conditional logic that can used to build these page builder widgets. Either it has to be broken down to do simpler stuff or else needs to be separated into a different widget.

**Comment by designbychris** [comment]
the issue is on a water treatment page, Laura wants to be able to select which specific microstories or blog posts to display, she doesn't want to rely on a category, she just wants to be able to call specific posts to display on the page.

It might be easier to make it into another widget, just didn't know if you could add this functionality to the current one :)

**Comment by samuelpyramidions** [comment]
@designbychris So if we have another widget that just allows you to select individual posts, would that do?

**Comment by samvthom16** [comment]
@designbychris the widget has been added and goes by the name - Akvo Pick Posts

**Comment by designbychris** [comment]
@samvthom16 this is great, but how do you select specific posts. You can still only select ones from specific dates / taxonomies etc.

Laura would like to be able to select a specific post from all the microstories etc. So we need to have a way to select the specific post, not just from a group of taxonomies / tags.

It almost needs to allow you to search for a post in a field as you would do from the Relationship field within ACF.  With that field you're able to select the posts by searching for hte name of the post/page/microstory.

Is that possible?

**Comment by samvthom16** [comment]
@designbychris This widget is specifically designed for picking individual posts. Try out the **post in** field.

**Comment by designbychris** [comment]
Ok.. will give it a test now, thanks for the update.

**Comment by designbychris** [comment]
Works great :D thanks @samvthom16
