### ISSUE TITLE
Add second featured image to Microstories CPT

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#309]
Hi @samvthom16 can we add a second Featured Image on the Microstories CPT so that we can call it in the related posts in the footer on the single.php file.

I need to be able to call the 2nd featured image in the code below thats used in the Related Posts  section of the single.php:

<?php while ( $query2->have_posts() ) : $query2->the_post(); 
				$advert_url = get_post_meta($post->ID, 'url', true);
				$featured_img_url = get_the_post_thumbnail_url(get_the_ID(),'full'); ?>
				<div class="col-lg-3 col-md-12 col-sm-12 col-xs-12 postpaddingbottom">
					<a href="<?php echo $advert_url ?>">
						<div class="col-lg-12 col-xs-12 advertbox" style="background:url(<?php echo $featured_img_url ?>);"></div>
					</a>
				</div>
				<?php endwhile; wp_reset_postdata(); endif; ?>

So if you can help with this that would be great :D

**Comment by samvthom16** [comment]
@designbychris I have added the second featured image for Microstories as well. This is how you can retrieve them in the templates:
`if( class_exists('MultiPostThumbnails') && MultiPostThumbnails::has_post_thumbnail( 'post', 'background_header_image') ) { 
			
			global $post;
			$image_id = MultiPostThumbnails::get_post_thumbnail_id( 'post', 'background_header_image', $post->ID ); 
			if( $image_id ){
				$image_src = wp_get_attachment_image_src( $image_id, 'full' );  
					
				if( is_array( $image_src ) ){
					$url = $image_src[0];
				}
			}
			
		}`

**Comment by designbychris** [comment]
Oh bugger.. can you add this functionality to the Adverts CPT.. sorry I had the wrong one! Bugger!

Sorry :(

**Comment by designbychris** [comment]
@samvthom16 can you let me know when the extra advert featured image has been added so that we can finish this task off?

**Comment by samvthom16** [comment]
@designbychris I have pushed the code

**Comment by designbychris** [comment]
@samvthom16 can you rewrite this section of code to call the correct image URL?
`<?php $query2 = new WP_Query( 'post_type=advert&order=asc&orderby=date&posts_per_page=1' ); ?>
				<?php if ( $query2->have_posts() ) :?>	
				<?php while ( $query2->have_posts() ) : $query2->the_post(); 
				$advert_url = get_post_meta($post->ID, 'url', true);
				$featured_img_url = get_the_post_thumbnail_url(get_the_ID(),'full'); 
				?>
				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 postpaddingbottom">
					<a href="<?php echo $advert_url ?>">
						<div class="col-lg-12 col-xs-12 advertbox" style="background:url(<?php echo $featured_img_url ?>);"></div>
					</a>
				</div>
				<?php endwhile; wp_reset_postdata(); endif; ?>`

It uses the featured_image_url syntax to call the featured image, if you could give me updated code to call the 2nd featured image instead that would be great :D

**Comment by samvthom16** [comment]
Use this code, inside the while loop:
if( class_exists('MultiPostThumbnails') && MultiPostThumbnails::has_post_thumbnail( 'post', 'background_header_image') ) { 
			
			global $post;
			$image_id = MultiPostThumbnails::get_post_thumbnail_id( 'post', 'background_header_image', $post->ID ); 
			if( $image_id ){
				$image_src = wp_get_attachment_image_src( $image_id, 'full' );  
					
				if( is_array( $image_src ) ){
					$url = $image_src[0];
				}
			}
			
		}

**Comment by designbychris** [comment]
@samvthom16 I have this code in the single.php, but its not displaying the Second Featured image.

Can you take a look at the single.php on line 96. This is where the loop is for the advert in the footer of the single.php is. I have a feeling i've either put it in the wrong place. Or i'm missing something to force it to change the image over.

**Comment by samvthom16** [comment]
@designbychris can you check if this is working now as expected?

**Comment by designbychris** [comment]
@samvthom16 the correct advert isn't being displayed. If you go here: 

https://akvo.org/blog/akvos-new-brand-identity/

and go to the bottom with the "You might also like..." section, and look at the advert, inspect the element, its showing as https://akvo.org/wp-content/uploads/2018/10/Ebook-Advert-2.jpg. In the backend of the site on the CPT post for this advert, the second featured image has been set as https://akvo.org/wp-content/uploads/2018/10/small-ebook-ad.png. So its not displaying the 2nd featured image on it.

Can you check again? :)

**Comment by samvthom16** [comment]
@designbychris I have updated the code. It seems working.

**Comment by designbychris** [comment]
@samvthom16 all seems happy now :) thanks
