### ISSUE TITLE
New site issues after go live

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#313]
Hi @samvthom16 there seems to be an issue when you search for e-book on the site, it comes up with this post: https://akvo.org/?advert=e-book-advert which I think is normal tbh. But I think that if possible we should hide the advert posts from the search results. As the actual post for the advert is https://datajourney.akvo.org/ebook-design-data-driven-development-programmes-that-deliver-results-effectively which isn't within the main akvo site, so can't be included on the site search.

My suggestion is to just hide the advert posts from the search results if possible.

**Comment by designbychris** [comment]
from Skype: We just noticed that the time for SEAP office is incorrect - it should be GMT+8 as that is the time in Bali

**Comment by designbychris** [comment]
Rotating Sentence addition - 

@samvthom16 if you take a look at the Akvo Rotating Sentence widget template.php, I have tried to add a div around the normal item information (the non fading element, the div is <div class="nofade">). Can you fix this for me, as its not surrounding the normal non animating text. I'm not sure why.

**Comment by samvthom16** [comment]
@designbychris I have removed the advert from the search results and updated the clock for SEAP. Can you confirm if this is working as expected?

**Comment by designbychris** [comment]
Looks good to me :)
