### ISSUE TITLE
WPFront notification bar

### ISSUE THREAD

**Issue by samvthom16** [akvo/Akvo-Theme#318]
@designbychris 
The toast has an ”x”-button but it doesn’t work for small screen sizes.

**Comment by designbychris** [comment]
hmm thats odd.. Let me take a look.. i'm wondering if we need it at all. Its only going to be up for a couple of weeks. I will take a look.

**Comment by designbychris** [comment]
Ok the button won't work on smaller screens, so I have disabled the button and made the bar disappear after 20 seconds instead. Its only needed for a couple of weeks, this will be fine :)
