### ISSUE TITLE
eq-col CSS

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#320]
@samvthom16 
We’re using eq-col1 and eq-col2 on the following pages, but it’s not showing yet

https://akvo.org/fr/ameliorez-et-mettez-en-valeur-les-resultats-de-votre-programme/
https://akvo.org/fr/saisir-et-interpreter-les-donnees-qui-comptent/
https://akvo.org/es/nuestro-enfoque/
https://akvo.org/es/mejorar-y-exponer-los-resultados-de-su-programa/
https://akvo.org/es/

**Comment by samvthom16** [comment]
@Lindaleunissen None of these pages have eq-col1 or eq-col2 set

**Comment by samvthom16** [comment]
@designbychris can you confirm if this working please?

**Comment by designbychris** [comment]
@Lindaleunissen can you check this for me?

**Comment by designbychris** [comment]
This looks all ok now to me
