### ISSUE TITLE
Blog posts additional functionality

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#322]
Hi @samvthom16 can you add a tick box on the blog post backend, to allow the administrator to hide the featured image from the single.php display. Not from the loop on the list but just on the single post.

**Comment by samvthom16** [comment]
@designbychris Need more context to understand what we are solving here. Also include some links as reference.

**Comment by designbychris** [comment]
Essentially what we need to be able to do is allow us to hide the featured image from the single.php with a tick box in the backend on the posts. I've done it on this post: https://akvo.org/blog/six-things-you-need-to-know-about-akvo-in-2019/ but I had to do it using CSS, ideally this should be controlled from within the post to allow the show/hide of the featured image from the post itself.

Does that help @samvthom16 ? :)

**Comment by samvthom16** [comment]
@designbychris Could you test this out for me please?

**Comment by designbychris** [comment]
I can't see this working @samvthom16 can you check and let me know where this is set within the post in the backend?

**Comment by samvthom16** [comment]
@designbychris had an issue with WP Pusher. You should find it now in the backend.

**Comment by designbychris** [comment]
@samvthom16 this now works :) thanks
