### ISSUE TITLE
Akvo Logo Slider Mobile issue

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#323]
Hi @samvthom16 can you take a look at something on mobile for me?

The logo slider on mobile goes a bit small and funny. I was wondering if there was a way to change the number of logos it shows when its on a screen size smaller than about 768px to show one at a time?

I think that this might be something that you can fix in the jQuery.

Can you take a look and let me know.

**Comment by designbychris** [comment]
Can we also sort a change for this on tablet size too? Maybe have it show a max of 4 on tablet sizes (probably up to 1000px or something like that).

**Comment by samvthom16** [comment]
$el.slick({
			slidesToShow	: $el.data('items'),
			slidesToScroll	: 1,
			autoplay		: true,
			autoplaySpeed	: 1500,
			arrows			: false,
			dots			: false,
			pauseOnHover	: false,
			responsive		: [{
				breakpoint	: 768,
				settings	: { slidesToShow: 4 }
			}, {
				breakpoint: 520,
				settings: { slidesToShow: 3 }
			}]
		});

**Comment by designbychris** [comment]
Ok that seems to be working, though I have changed it to 2 on the 520 breakpoint.. its not working as of yet. But it might just be a caching thing. So i'll check back later.
