### ISSUE TITLE
Akvo Rotating Text mobile issue

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#324]
Hi @samvthom16 can you take another look at this widget on mobile.. as its having an issue again where the rotating text won't stay inline with the rest.

Can you have a look at this, I will also see if I can fix it with CSS. Just thought that you may have a solution.

**Comment by samvthom16** [comment]
@designbychris Please include some links for me to test the different use cases

**Comment by designbychris** [comment]
@samvthom16 please see the attached from my iPhone. If you go to the https://akvo.org/safe-water-for-all/ page on your mobile you will see the issue.

**Comment by designbychris** [comment]
![img_2333](https://user-images.githubusercontent.com/2072475/53892278-e6b27980-4023-11e9-835c-9551637495a5.PNG)
![img_2334](https://user-images.githubusercontent.com/2072475/53892280-e6b27980-4023-11e9-8173-4fa0354fae45.PNG)

**Comment by designbychris** [comment]
they just don't seem to want to line up with each other :( even though they are both set to display:inline :(

**Comment by samvthom16** [comment]
@designbychris .nofade is not set to inline. That would set them to a single line.

**Comment by designbychris** [comment]
@samvthom16 hmm yes. this isn't perfect.. I may have to look for an alternative way to achieve this which is more responsive friendly. Currently it works, but on some sizes it has issues.

I will review this with Linda. 

I have set .nofade to inline again now (strangely it was set to inline. I must've removed it at some point lol)
