### ISSUE TITLE
Apply Modal issue

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#330]
Hi @samvthom16 can you take a look at this page:

https://akvo.org/join-our-team/ 

We seem to have an issue with the last job on the list. It seems to not be happy and won't open up the modal window.

Can you take a look and see what the problem is?

**Comment by samvthom16** [comment]
@designbychris This is a tricky issue. The problem was since the data inside the modal of the button was the same, it was creating same ID for all the modal. That's why I had to introduce some hidden data in the content to create unique IDs. It seems to be working now.

**Comment by designbychris** [comment]
Yeah not sure what the problem was, but it seems to be ok now :)
