### ISSUE TITLE
Force https issue

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#341]
Hi @samvthom16 can you check something for me.

Laura is having an issue. When she types in the akvo.org url its not forcing https:// on some pages.

Namely when she types in akvo.org/newsletter into her browser.

Can you have a look and see if there is an issue on the htaccess or something like that not forcing https?

**Comment by samvthom16** [comment]
Everytimes the SSL certificate is auto renewed the settings get flushed which needs to be updated to force redirect to https.
