### ISSUE TITLE
Harmonica content not showing in last tab on terms page

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#346]
I've entered content in the wordpress for the 'Version History' harmonica tab, however, this is not showing on the actual page. See screenshots below of backend and front end. 
<img width="1216" alt="Screenshot 2019-04-08 at 15 33 11" src="https://user-images.githubusercontent.com/5338081/55732331-b50e4300-5a13-11e9-922f-4c946d18eff4.png">
<img width="1585" alt="Screenshot 2019-04-08 at 15 33 25" src="https://user-images.githubusercontent.com/5338081/55732335-b6d80680-5a13-11e9-9a45-70952fae417b.png">

**Comment by designbychris** [comment]
@samvthom16 can you take a look at this?

**Comment by samvthom16** [comment]
@Lindaleunissen please share the link

**Comment by Lindaleunissen** [comment]
https://akvo.org/terms-of-service

**Comment by samvthom16** [comment]
@Lindaleunissen fixed this. The problem is when you copy paste content in the visual editor, it copies the content as it is with the html code. And the html code confuses the browser as it screws up with the semantics of the site. 

Solution - copy paste into the text tab of the visual editor.

**Comment by Lindaleunissen** [comment]
Clear! Thanks for fixing it Sam!
