### ISSUE TITLE
Team page re-order

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#347]
In the past we were able to adjust the order team member appear in on the team page. We seem to have lost that functionality with the new website. @samvthom16 I believe you were looking into this already, but since I cannot find an issue, adding it here now.

**Comment by samvthom16** [comment]
@Lindaleunissen  I have updated the live site with the appropriate plugin. Can you please confirm this for me?

**Comment by Lindaleunissen** [comment]
Yes works! Thanks Sam!
