### ISSUE TITLE
Logo carousels on devices

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#348]
The logo carousel on my (i)Phone now only shows 2 logos at a time in portrait mode, and 4 in landscape mode, which is perfect. 

On my tablet (iPad Mini) however it shows 5 logos in both portrait and landscape mode. Can we also set that to reduce according to width? Maybe 3 in portrait mode?

Thanks!

**Comment by designbychris** [comment]
@samvthom16 I think you set something for this. We may need to add a few more options to allow for this.

**Comment by samvthom16** [comment]
@designbychris existing breakpoints are these - 
breakpoint for 768, slidesToShow: 4
breakpoint: 520, slidesToShow: 2 

Please give me exact number of items for each breakpoint

**Comment by designbychris** [comment]
@samvthom16 if you look at the comment from @Lindaleunissen she says that she would like to have 3 in portrait mode on iPad. So it might be that you add another breakpoint at 960px or something like that for 4 to show and then at 768 you have 3 then at 520 you have 2.

Does that help?

**Comment by samvthom16** [comment]
@Lindaleunissen I have updated the breakpoints

**Comment by Lindaleunissen** [comment]
Perfect! Thanks!
