### ISSUE TITLE
Advert distorting

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#349]
On my tablet (iPad Mini) the advert on the backstage blog is severely distorted. See screengrabs in landscape and portrait mode below.

![IMG_1881](https://user-images.githubusercontent.com/5338081/55783782-221ee880-5aa7-11e9-9c70-dbd42cf710e5.JPG)
![IMG_1880](https://user-images.githubusercontent.com/5338081/55783788-23e8ac00-5aa7-11e9-95a9-04359a56e1a3.JPG)

**Comment by samvthom16** [comment]
@Lindaleunissen I have updated the image size. Please can you confirm this?

**Comment by Lindaleunissen** [comment]
Distorting on iPad mini is still the same. I don't think it's the image size, rather the way the image is scaled down on the page, which is currently not done evenly.

**Comment by samvthom16** [comment]
@Lindaleunissen will have to get on a call for this.

**Comment by samvthom16** [comment]
1. The text is included within the image. 
2. The image aspect ratio has to be maintained as per the screen width

**Comment by Lindaleunissen** [comment]
It's currently also distorting on desktop. Ignore the text please, I can lay out a new image once I understand how the image is scaled down, but the image should not distort under any circumstance. Either scale it down or trim it.

**Comment by samvthom16** [comment]
@Lindaleunissen lets get a call on this on thursday because there are far too many overriding styles written for the same element that I can't figure what was the original plan. Also there is far too much blank space in the image itself that doesn't serve as a good reference.

**Comment by samvthom16** [comment]
@Lindaleunissen I have updated the code to show the image without any trimming or scaling. I think the blank space within the image does not distinct itself.

**Comment by Lindaleunissen** [comment]
Perfection. Thanks Sam.
