### ISSUE TITLE
rotating sentence on impact area pages

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#350]
On smaller screens the breaking of the sentence is odd, stacking words on top of each other, rather than on a new line. We could possible break the sentence earlier (just before 'we need', which could avoid this on screens.

On my phone (iPhone 8) the text breaks fine, but the font is too small in portrait mode. See first image below

On my tablet (iPad mini) the sentence is wider than the screen, enabling a horizontal scroll. De background colour disappears, making the words illegible. See second and third image below

1
![IMG_8502](https://user-images.githubusercontent.com/5338081/55784303-32839300-5aa8-11e9-8623-272edb0060a6.PNG)

2
![IMG_1882](https://user-images.githubusercontent.com/5338081/55784626-dcfbb600-5aa8-11e9-9668-773a714f3ac5.JPG)
3
![IMG_1883](https://user-images.githubusercontent.com/5338081/55784622-da995c00-5aa8-11e9-8d30-a826a6909953.JPG)

**Comment by samvthom16** [comment]
#324 Duplicate Issue

**Comment by samvthom16** [comment]
@Lindaleunissen if the rotating phrases can be displayed on the next line then I can create a foolproof mechanism for them to work across all screen sizes without them breaking as I need to fix the width of that entire container. Right now the width is varying based on the phrase size.

**Comment by Lindaleunissen** [comment]
I'm happy with that. 
There's still a risk of it looking odd. For instance a line with only one word before the rotating text, but we'll cross that bridge when (if) we get there.

**Comment by samvthom16** [comment]
@Lindaleunissen can work on an alternative like this - 
https://codepen.io/gschier/pen/jkivt

**Comment by Lindaleunissen** [comment]
Love that, and definitely would like to keep that in mind for the future, but in this case I think our sentences are too long for this treatment. 
I'm happy for you to put the rotating phrases on the next line, and then we'll take it from there. :)

**Comment by samvthom16** [comment]
@Lindaleunissen found a better workaround without the need of the next line but maybe the animation is too fast, what do you think?

**Comment by Lindaleunissen** [comment]
It's a bit fast, but looking good! If you can slow it down, then please do. If not, then leave it like this for now. Thanks @samvthom16 !
