### ISSUE TITLE
font size bulleted paragraph on single blog post

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#351]
https://akvo.org/blog/six-things-you-need-to-know-about-akvo-in-2019/

Right at the bottom of that blog Alvaro used bullet points. The font size of those is smaller than the normal font size, even though both are set to 'paragraph'.
(I think this problem might not be limited to the blog, but we haven't used bullets elsewhere.. )

Can you please set it so that bulleted text is the same size are normal text?

**Comment by samvthom16** [comment]
@designbychris There are too many conflicting styles regarding font-sizes. For example, body has a different font-size that is being inherited in the bulleted paragraph which is different from the post content. Is there a way we can resolve these conflicts by separating the different sets of font sizes than overriding?

**Comment by designbychris** [comment]
@samvthom16 this was done because I was asked to make fonts different sizes on different sections to make them stand out more. If there is a specific section that needs to have specific font sizes, then I will need to make an override or spend time fixing ALL the font sizes across the board, which will take time. @Lindaleunissen will need to decide on this (after Alvaro has worked out budgets etc).

**Comment by Lindaleunissen** [comment]
@Chris, I thought in the end we decided that the paragraph font would be the same size across the site? 
How much time would it take to change that?

**Comment by designbychris** [comment]
@Lindaleunissen I thought that it was too.. unless something else has happened. I think it would take me an hour to sort out the override of all paragraph fonts across the site. But we might need more time after this is done, in case we have something going wrong somewhere.

If you want me to have a look at it, I have time on Monday next week :)

**Comment by Lindaleunissen** [comment]
@designbychris Thanks. Let me chat to Alvaro first. Will let you know when I get a go ahead.

**Comment by designbychris** [comment]
No worries :)

**Comment by samvthom16** [comment]
@Lindaleunissen have done a quick fix for the time being. Can you confirm please?

**Comment by Lindaleunissen** [comment]
Much better. Thanks @samvthom16
