### ISSUE TITLE
Moving GIFs do not display in blog post on mobile

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#352]
https://akvo.org/blog/akvos-new-brand-identity/

The moving GIF looks fine on screen, but on my phone (iPhone 8) the GIF is not visible.

**Comment by samvthom16** [comment]
@Lindaleunissen the problem is that on the image section a margin of 200 px has been given which extremely reduces the rendering space for the image.

**Comment by Lindaleunissen** [comment]
Thanks @samvthom16. Unfortunately now the gifs are static and not moving anymore (both on desktop and mobile). Could that have anything to do with the changes you made?

**Comment by samvthom16** [comment]
Should be working now.

**Comment by Lindaleunissen** [comment]
Yes! thanks
