### ISSUE TITLE
Anchor on policies page

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#353]
For GDPR reasons we need to have the Data Protection Agreement (DPA) clearly visible and easy to find. I was wondering if we can do the following:

Can we have a link that is Akvo.org/dpa which will take you to this page: https://akvo.org/policies, but with an anchor on the open DPA harmonica tab?

Thanks!

**Comment by samvthom16** [comment]
@Lindaleunissen this is not possible within the current siteorigin accordion widget. For inline section links, we need IDs for that particular section which the widget does not provide.

**Comment by Lindaleunissen** [comment]
OK. The redirect already helps loads. Thanks Sam!
