### ISSUE TITLE
Stat widget design

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#354]
The statistics widget on the homepage (1A) and on the microstory page (1B) is the same widget with some additional code on the homepage to change the look of it. 
The stats widget on the impact area pages (2) is a different one. It looks like 1A without an icon, but the font size is different. 

Can you please do the following?
1) Keep widget 1B as it is. 

2) Make 1A into a 'standard' widget which we can copy to other pages without it needing additional coding like it does at the moment. If we can do that, I can use widget 1A in stead of widget 2 (just without an icon), therefore making sure they have the same font sizes etc. 

3) Widget 2 would then be redundant.

**Comment by samvthom16** [comment]
@Lindaleunissen please can you share the links of the same. So far I know that we have only built one stats widget. The other widget being used as the stats widget is the featured widget which is one of the default widgets that comes with the page builder package.

**Comment by Lindaleunissen** [comment]
Widget 1B on microstory page:
https://akvo.org/stories/west-africa/designing-a-water-quality-monitoring-system-in-sierra-leone-with-unicef/
<img width="1229" alt="Screenshot 2019-04-11 at 14 20 30" src="https://user-images.githubusercontent.com/5338081/55960598-0b25f500-5c65-11e9-9e6c-ef7690c0aadd.png">

This is the same widget as on the homepage (1A), but on the homepage it has added code by Chris:
https://akvo.org/
<img width="1249" alt="Screenshot 2019-04-11 at 14 21 55" src="https://user-images.githubusercontent.com/5338081/55960675-301a6800-5c65-11e9-8c8f-54c10c5c8ff7.png">

Widget 2
Looks similar, but is less nicely laid out. 
https://akvo.org/safe-water-for-all/ and https://akvo.org/sustainable-smallholder-farming/
<img width="1251" alt="Screenshot 2019-04-11 at 14 23 09" src="https://user-images.githubusercontent.com/5338081/55960775-59d38f00-5c65-11e9-8ff4-5df1ff321872.png">

**Comment by samvthom16** [comment]
@Lindaleunissen you can test the stats widget here: https://akvo.org/wp-admin/post.php?post=52686&action=edit&lang=en

There is a new option - theme added to the widget settings

**Comment by Lindaleunissen** [comment]
Perfect!

**Comment by Lindaleunissen** [comment]
Updated the widget on all affected pages.
