### ISSUE TITLE
Header menu on tablet

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#357]
If I hold my iPad Mini in portrait mode, the header menu takes up double height, and allows for horizontal scrolling again. This was not an issue a few days ago, so might have something to do with the changes you made. Maybe we should set it to go to mobile view, with the hamburger symbol instead?

![IMG_2592](https://user-images.githubusercontent.com/5338081/55961700-5e00ac00-5c67-11e9-8191-3446abff9b9e.PNG)

**Comment by samvthom16** [comment]
@Lindaleunissen The issue is with the translation options that are displayed as a horizontal list, while testing they were a dropdown.

**Comment by Lindaleunissen** [comment]
@samvthom16 That's fine, but now that's been changed, can set it so that in portrait view on tablet the header menu behaves the same as on a mobile phone?

**Comment by samvthom16** [comment]
@Lindaleunissen lets get a call on this on thursday because there are far too many overriding styles written for the same element that I can't figure what was the original plan.

**Comment by samvthom16** [comment]
@Lindaleunissen have updated the code. Can you please confirm this one?

**Comment by Lindaleunissen** [comment]
Yes, all good. Thank you!
