### ISSUE TITLE
Text width on mobile

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#358]
On mobile (iPhone 8) the text on the homepage in the ebook section only takes up half the width of the screen. Can you please have a look at that?

![IMG_8514](https://user-images.githubusercontent.com/5338081/55962432-c13f0e00-5c68-11e9-8801-d7e1fe8d3951.PNG)

**Comment by samvthom16** [comment]
@Lindaleunissen the collapse option was set to none for this row, it had to be set to standard. Can you confirm if this works for you?

**Comment by Lindaleunissen** [comment]
Much better. Thanks @samvthom16
