### ISSUE TITLE
Translations within the theme

### ISSUE THREAD

**Issue by samvthom16** [akvo/Akvo-Theme#360]
Where on website? | EN | ES | FR

Americas and West Africa regional pages | Want to visit one of our other offices? | ¿Quieres visitar una de nuestras oficinas? | Souhaitez-vous visiter un autre de nos bureaux ?

Clocks | Americas | Américas | Les Amériques

Clocks | West Africa | África Occidental | L’Afrique de l’Ouest

Clocks | East Africa | África Oriental | L’Afrique de l’Est

Clocks | South Asia | Asia del Sur | L’Asie du Sud

Clocks | South East Asia and Pacific | Sudeste Asiático y el Pacífico | L’Asie du Sud-Est et du Pacifique

Clocks | Europe | Europa | L’Europe

Header | Type keyword(s) here | Escribe aquí lo que buscas | Saisissez le(s) mot (s) clé(s) ici

Header | Search | Buscar | Rechercher

Footer | Explore resources | Explorar recursos | Explorez les ressources

**Comment by samvthom16** [comment]
@Lindaleunissen - I have added the translations. In case you want to update them, you can do it from here: https://akvo.org/wp-admin/admin.php?page=wpml-string-translation%2Fmenu%2Fstring-translation.php&context=akvo

**Comment by Lindaleunissen** [comment]
Nice one Sam. Thanks!
