### ISSUE TITLE
Metadata not showing up on Google

### ISSUE THREAD

**Issue by samvthom16** [akvo/Akvo-Theme#362]
The metadata is filled in in Wordpress but not showing on Google - hope screenshots make issue clear! Same in FR and ES. 
![Screen Shot 2019-04-16 at 14 53 45 - Georgia Walker](https://user-images.githubusercontent.com/1712132/56338300-2ba30180-61c7-11e9-89ea-c0ec0cbd636a.png)

**Comment by samvthom16** [comment]
So far the og tags are coming out correct, debugged here - https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fakvo.org%2Fcapture-and-understand-data-that-matters%2F

**Comment by samvthom16** [comment]
https://support.google.com/webmasters/answer/7489871?hl=en

**Comment by samvthom16** [comment]
Updated the robots.txt to
User-agent: *
Allow: /

**Comment by samvthom16** [comment]
@Lindaleunissen this has been fixed. You can also test it from your end.

**Comment by Lindaleunissen** [comment]
Works!
Thanks @samvthom16
