### ISSUE TITLE
Please update Font aAwesome plug in

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#373]
I've just used a new Font [awesome icon](https://fontawesome.com/icons/sack-dollar?style=regular) on [this page](https://akvo.org/wp-admin/post.php?post=52809&action=edit&lang=en).

It's currently not showing, which usually means Font Awesome has had an update. 
could you look into that for me?

Thanks @samvthom16 !

**Comment by samvthom16** [comment]
@Lindaleunissen I have updated the library. Its working now.

**Comment by Lindaleunissen** [comment]
That works. Thanks!
I've noticed that on [this micro story page](https://akvo.org/stories/east-africa/using-citizen-science-to-monitor-the-health-of-nairobis-rivers/) The opening quote marks on the testimonial (blue block) are displayed as a little square. Could that be due to the update? Please have a look?

**Comment by samvthom16** [comment]
@Lindaleunissen Yes Linda, it was the update. I had to upgrade the styles for this in the theme.

**Comment by Lindaleunissen** [comment]
Briliant. Thank you @samvthom16

**Comment by Lindaleunissen** [comment]
Brilliant. Thank you @samvthom16

**Comment by Lindaleunissen** [comment]
Hi Sam, 

Just noticed that the linked in and twitter icons on the team page have disappeared
https://akvo.org/who-we-are/meet-our-team/

Please have a look when you can?
Thanks!

**Comment by samvthom16** [comment]
@Lindaleunissen Have fixed those icons. It seems that the new version has changed how the old brand icons were being loaded.

**Comment by Lindaleunissen** [comment]
Brilliant. Thank you!

**Comment by Lindaleunissen** [comment]
I found another place where the icons aren't showing correctly. Could you have a look at the footer section?
Thanks!

**Comment by samvthom16** [comment]
@Lindaleunissen 
The footer icons have also been fixed
