### ISSUE TITLE
Read my blogs on team page

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#375]
Hi Sam,

If I click on 'Read my blogs' on this page https://akvo.org/who-we-are/meet-our-team/
it no longer takes you to a personal blog overview, but to the link below. Could you please find out what's happening there?
https://akvo.org/bloghttps:/akvo.org/who-we-are/meet-our-team/

Thanks, Linda

**Comment by samvthom16** [comment]
@Lindaleunissen There was a redirect that was causing all the author pages to the team page. I have disabled that redirect. 

I just noticed that these posts don't have any featured images: https://akvo.org/blog/author/jeroen/. Should we use a default one?

**Comment by Lindaleunissen** [comment]
It used to show the default image there. Not sure why not anymore, but in short, yes please!

**Comment by samvthom16** [comment]
Fixed default featured image with the help of a plugin
