### ISSUE TITLE
Akvo bullet list widget

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#389]
On the pricing page (https://akvo.org/wp-admin/post.php?post=54341&action=edit&lang=en)
we've got the bullet list widget that you build for us. Could you make some changes to that?

1 - We'd like to be able to change the colour of the icon and first column of text
2 - We'd like fading to be separate from the text colour change. 

So in practice I want to be able to set the text to all black or with a green header, and choose separately whether or not this text is faded.

**Comment by Lindaleunissen** [comment]
At the moment the widget is set up as follows. 
I enter text in the widget, which on the website automatically shows as blue and black:
<img width="917" alt="Screenshot 2019-12-19 at 11 18 10" src="https://user-images.githubusercontent.com/5338081/71169621-4abfca80-2251-11ea-9f05-809914172f78.png">

For each line in the widget I can choose to check the box called faded, which automatically makes the text colour black, and the text faded. On hover the text will go solid:
<img width="915" alt="Screenshot 2019-12-19 at 11 18 21" src="https://user-images.githubusercontent.com/5338081/71169724-878bc180-2251-11ea-88cf-07fc525e76ef.png">


What we would like is to be able to change the text colour for the items that are 'normal' (faded box not checked). That way we can use this widget on other pages, where we want a different colour than blue (for example green and black) (This refers to point 1 of the comment above).

We like to keep the faded checkbox option, but without the colour change. So that if we have a green and black text above (or whatever colour), it stays that way when we check the faded box. The only thing the faded checkbox does, is set the text to faded (and solid on hover), but it doesn't change the colour of the text as it currently does. (Point 2 in the comment above).

**Comment by psychome004** [comment]
https://github.com/akvo/Akvo-Theme/commit/ca6c39f3c79cc283205c1f0b308ad0ec13fbb13a 
Updated akvo-bullet-list-sow

**Comment by Lindaleunissen** [comment]
Works! Thanks!
