### ISSUE TITLE
Line spacing (New homepage)

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#391]
We've build a new homepage in the backend, that needs some tweaks before it can go live. Homepage wp link: https://akvo.org/wp-admin/post.php?post=55636&action=edit&lang=en

In the section named 'two fields' we used two different heading sizes to display a title and a subtitle. Because they are both titles, the spacing between the two lines looks off - it's slightly to large. Can you reduce that by approximately 25%?

**Comment by samvthom16** [comment]
@Lindaleunissen Can you confirm if the fix has worked?

**Comment by Lindaleunissen** [comment]
Looks amazing. Thank you!
