### ISSUE TITLE
New trust block (New Homepage)

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#393]
We've build a new homepage in the backend, that needs some tweaks before it can go live. Homepage wp link: https://akvo.org/wp-admin/post.php?post=55636&action=edit&lang=en

In the row called 'trust block' it currently shows a logo carousel. We'd like this row be a combination of two widgets we already have. 

On the left we'd like 3 spots for metrics - like the vanity metrics row we have on the current homepage. 

On the right we'd like a logo carousel, but one that only shows 2 logos at a time, and then slides through like the current logo carousel does, 

I tried combining these 2 widgets myself by making the row multi-column, but it didn't work. Could you have a look and see what you can do?

**Comment by samvthom16** [comment]
@Lindaleunissen can you confirm if this is working now?

**Comment by Lindaleunissen** [comment]
It works, but we might have to tweak a few things so it looks better visually. I'll get back to you regarding that.

**Comment by Lindaleunissen** [comment]
Let's park this for now.
