### ISSUE TITLE
New footer

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#397]
With the launch of the new homepage, we also want to update the footer of the website. 

The new footer is basically a collection of hyperlinks grouped in 6 columns. Please see the mock up attached. 

<img width="1102" alt="Footer" src="https://user-images.githubusercontent.com/5338081/73770282-0e4e1c80-4774-11ea-892d-e32817f0a542.png">

**Comment by samvthom16** [comment]
@Lindaleunissen my only concern with the design is that it might get cluttered for medium screen sizes. Also the menu item "Sustainable smallholder farming", in which the second line is indented cannot be achieved as there are no straightforward css rules for that.

**Comment by Lindaleunissen** [comment]
@samvthom16 Can we stack the footer on smaller screens? Maybe have 3 columns and 2 rows. And on even smaller screens, 2 columns and 3 rows?

As for the longer menu items, (sustainable smallholder farming) this was just an idea of how to show it's one item rather than two. This could also be achieved in different ways, for instance by increasing the line height in between links so that the text of a link that is broken up over two lines is closer together.
