### ISSUE TITLE
Homepage header image text

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#398]
On the homepage we'd like the text on the main image to stand out a bit more. The positioning needs to change and the colour palette too. Additional a button needs to be overlaid on the image. This should be a HubSpot generated button. 

For new lay-out please see image attached. The text is 90% final, but should be editable in the backend. 

For future use across the rest of the website, it would be good if we can set the colours for the header text in the backend, rather than them coming up as while/green as a new standard. 

<img width="1101" alt="Homepage header image text" src="https://user-images.githubusercontent.com/5338081/73839469-fdea8000-480d-11ea-917c-97572eb207ab.png">

**Comment by Lindaleunissen** [comment]
Link to the wordpress where I've started building the page as far as I could. 
https://akvo.org/wp-admin/post.php?post=56455&action=edit&lang=en

**Comment by samvthom16** [comment]
@Lindaleunissen I see that a widget already exists in the backend: Akvo Slider. You want the above customisation options in the same widget right?

**Comment by Lindaleunissen** [comment]
Yes, I reckon that would be the best option.

**Comment by samvthom16** [comment]
@Lindaleunissen for me to test the hubspot button, I need an embed from hubspot that we can use

**Comment by Lindaleunissen** [comment]
@samvthom16 Here is the button embed code:
<span class="hs-cta-wrapper" id="hs-cta-wrapper-c121e58b-7132-4e02-8aa7-db4122167850"><span class="hs-cta-node hs-cta-c121e58b-7132-4e02-8aa7-db4122167850" id="hs-cta-c121e58b-7132-4e02-8aa7-db4122167850"><a href="https://cta-redirect.hubspot.com/cta/redirect/1891949/c121e58b-7132-4e02-8aa7-db4122167850" ><img class="hs-cta-img" id="hs-cta-img-c121e58b-7132-4e02-8aa7-db4122167850" style="border-width:0px;" src="https://no-cache.hubspot.com/cta/default/1891949/c121e58b-7132-4e02-8aa7-db4122167850.png"  alt="Request a consultation"/></a></span><script charset="utf-8" src="https://js.hscta.net/cta/current.js"></script><script type="text/javascript"> hbspt.cta.load(1891949, 'c121e58b-7132-4e02-8aa7-db4122167850', {}); </script></span>

If you need to edit anything in hubspot (colours maybe?) you can do so here:
https://app.hubspot.com/ctas/1891949/edit/c121e58b-7132-4e02-8aa7-db4122167850

**Comment by Lindaleunissen** [comment]
Ok, looks like Hubspot has interpreted some of that code. I'll put it in a form and send it over to you, so you have the complete thing.

**Comment by Lindaleunissen** [comment]
The latest update on this widget has caused a problem on another page. https://akvo.org/contact-us/get-in-touch/ ( or https://akvo.org/wp-admin/post.php?post=48625&action=edit&lang=en)

I managed to set the colour on the get in touch page back to black and white, which works really easily. But I can't set the alignment. At the moment the Get in touch aligns to the right. I'd like it to align to the left (as it does on every page except for the homepage) but seem to be unable to.

**Comment by Lindaleunissen** [comment]
@samvthom16 At the moment the text on the new homepage still isn't centred to the page. 

We're also still missing the button overlaying the image.

**Comment by samvthom16** [comment]
@Lindaleunissen updated this, are the styles of the button okay?

**Comment by Lindaleunissen** [comment]
@samvthom16 Can you make the outline of the button white? Otherwise it's all good!

**Comment by samvthom16** [comment]
@Lindaleunissen fixed. Can we close this?

**Comment by Lindaleunissen** [comment]
Absolutely! Thank you!

**Comment by Lindaleunissen** [comment]
Hi Sam, I reopened this issue, as I just realised that the headers on ALL pages have changed in size and colour. Only the homepage should show this new header style for now, everything else should've remained looking the same. When we are updating pages we might want to update the header style too, but for the moment we don't.

**Comment by samvthom16** [comment]
@Lindaleunissen reverted to the default settings.

**Comment by Lindaleunissen** [comment]
Brilliant. Thanks!

**Comment by Lindaleunissen** [comment]
@samvthom16 Can you set the header on the blog to look like the 'standard' treatment too? At the moment that is set the same way as the homepage, and I can't change the blog header myself. 

I'm talking about this page: https://akvo.org/blog/

It should look like this link: https://akvo.org/blog/akvo-is-looking-for-a-new-ceo/

Thanks!

**Comment by samvthom16** [comment]
@Lindaleunissen can you share a screenshot of what you see here: https://akvo.org/blog/

**Comment by Lindaleunissen** [comment]
It's all looking good now! Thank you!
