### ISSUE TITLE
Homepage value stack

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#399]
On the new homepage, just under the main image we show a value stack; 3 benefits of using Akvo. https://akvo.org/wp-admin/post.php?post=56455&action=edit&lang=en

To make the values to stand out more individually we'd like a vertical line in between each of them. A subtile white line should do the trick. See attached mock up. 

![Value stack](https://user-images.githubusercontent.com/5338081/73840996-730b8480-4811-11ea-9114-6152d9090e85.jpg)

**Comment by samvthom16** [comment]
@Lindaleunissen can you confirm if this working?

**Comment by Lindaleunissen** [comment]
Looks great. Thank you!
