### ISSUE TITLE
Link on header text

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#400]
On the [new homepage](https://akvo.org/wp-admin/post.php?post=56455&action=edit&lang=en
) in the design-capture-understand-act section - (value proposition)

We've used a link on a header 4 (with class thin). At the moment the link is underlined only on hover. Can you make that line show even without hovering over to highlight that there is a link there?

<img width="1096" alt="Link under data journey" src="https://user-images.githubusercontent.com/5338081/73841848-53755b80-4813-11ea-83d6-4c30d93bd78b.png">

**Comment by samvthom16** [comment]
@Lindaleunissen have updated this. Please confirm if this works.

**Comment by Lindaleunissen** [comment]
Beautiful. Thanks!
