### ISSUE TITLE
Connect step icons with horizontal line

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#401]
On the [new homepage ](https://akvo.org/wp-admin/post.php?post=56455&action=edit&lang=en
) there is a section called "the plan".

Under the header "Start today" there are 3 icons that show the steps people need to take to start working with us. It would be nice if there were horizontal white lines between the icons to show the steps are connected. 

<img width="1102" alt="3 steps to take" src="https://user-images.githubusercontent.com/5338081/73842237-13fb3f00-4814-11ea-8072-a8577df9c54f.png">

**Comment by samvthom16** [comment]
@Lindaleunissen do you have a reference link? I'm not sure how the horizontal line would cut through individual isolated columns and at the same time keeping this responsive.

**Comment by Lindaleunissen** [comment]
I stole the idea from [this website](https://www.mistercoverletter.com/). There is a plan section further down the page, which shows step 123.

**Comment by samvthom16** [comment]
@Lindaleunissen We have pushed this widget on live. Can you please confirm if this is working?

**Comment by Lindaleunissen** [comment]
Looks wonderful. Thank you!
