### ISSUE TITLE
Read more/less links on explanatory paragraph

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#402]
On the [new homepage](https://akvo.org/wp-admin/post.php?post=56455&action=edit&lang=en)
There is an explanatory paragraph. At the moment the full paragraph is showing. 

Instead we'd like a read more link at the end of the first paragraph, that will unfold the rest of the copy on the same page. 
<img width="1104" alt="Explanatory text - read more" src="https://user-images.githubusercontent.com/5338081/73844238-165f9800-4818-11ea-86b9-302f4ff069e8.png">

When folded out there should be a button at the end of the copy that'll allow the reader to fold the text back in. 
<img width="881" alt="Explanatory text - read less" src="https://user-images.githubusercontent.com/5338081/73844243-18c1f200-4818-11ea-8f10-ad685bd256ee.png">

**Comment by samvthom16** [comment]
@Lindaleunissen we have updated this page. Can you confirm if this works?

**Comment by Lindaleunissen** [comment]
Works great. Thank you!
