### ISSUE TITLE
Third parties page

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#403]
On the old version of Akvo.org we had a third parties page. It was basically a standard page that pulled in data from a google spreadsheet. 

We need that page back. I'm thinking Akvo.org/thirdparties 

The spread sheet can be found [here](https://docs.google.com/spreadsheets/d/1YiFD0qcQrep_4sPRf9yciG-riUOohSf7SnlBLgY52qM/edit#gid=0)

I currently don't have editing rights to this page, but have requested them so I can set fonts to fit with our current website style. 

Let me know if you need me to create a page in the backend, and anything else you may need to make this work.

**Comment by Lindaleunissen** [comment]
Update: I now have editing rights and have done some basic font changes, etc. which we can adjust further if necessary.

**Comment by samvthom16** [comment]
@Lindaleunissen Hello Linda I would need more context to this issue since I wasn't aware of the page in the old version.

**Comment by Lindaleunissen** [comment]
I'm not sure I can give you more context. It's something Lynn set up I think. It was basically a google sheet that was displayed (view only) on the website. I'm guessing through a plug in?

**Comment by Lindaleunissen** [comment]
It's basically so that if the sheet gets updated, the page will automatically sync. I reckon [this plugin](https://embedpress.com/docs/embed-google-sheets-wordpress/) might work? There might be better ones available though.

**Comment by Lindaleunissen** [comment]
@samvthom16 
I've got a request from the management team to get this page live. The link that needs to be displayed is https://docs.google.com/spreadsheets/d/1YiFD0qcQrep_4sPRf9yciG-riUOohSf7SnlBLgY52qM/edit#gid=0

And the ideal URL for this page would be akvo.org/third-parties. 

Can you make that happen?
Thanks!

**Comment by samvthom16** [comment]
@Lindaleunissen to embed the page I would need editing rights to the document.

**Comment by Lindaleunissen** [comment]
Done!

**Comment by samvthom16** [comment]
@Lindaleunissen embedded the sheet here: https://akvo.org/wp-admin/post.php?post=57360&action=edit&lang=en

**Comment by Lindaleunissen** [comment]
Thank you!

I'm trying to add a colourful header to the page, like we have on other pages, but it doesn't show?

Also the fonts seem to have defaulted to Arial or Helvetica, even though I've set the file up in the correct font. 

Anything you can do about that?

**Comment by samvthom16** [comment]
@Lindaleunissen I have fixed the header. Can you please send me a screenshot from where you set the correct fonts in the sheet?

**Comment by Lindaleunissen** [comment]
@samvthom16 Thanks for this. Header looks great. 
I've set the fonts correctly in the original google doc. They seem to get converted when it displays on the website. 

https://docs.google.com/spreadsheets/d/1YiFD0qcQrep_4sPRf9yciG-riUOohSf7SnlBLgY52qM/edit#gid=0

**Comment by samvthom16** [comment]
https://support.google.com/sites/thread/12258111?hl=en

**Comment by Lindaleunissen** [comment]
Thanks for that Sam. It worked on the old site though? Maybe that was a different plugin? Is there any way we can find out what was used then?

**Comment by samvthom16** [comment]
@Lindaleunissen hello Linda I'm still working on it. That was for my reference :)

**Comment by Lindaleunissen** [comment]
@samvthom16 Now the homepage is done, could you please have another look at this issue? Happy to help with anything you need.

**Comment by samvthom16** [comment]
@Lindaleunissen used another plugin this time. Can you confirm if the this is working?

**Comment by Lindaleunissen** [comment]
@samvthom16 
Thanks for this. The formatting works, as it currently shows the right fonts, etc. 

However, it almost looks like an iframe? I can see the entire interface of google sheets, I can even log in and make changes, which looks odd. Is there any way you can hide that upper bit of the frame?

Thanks!

**Comment by samvthom16** [comment]
@samvthom16 please check again

**Comment by Lindaleunissen** [comment]
@samvthom16 Looks fantastic. Thank you!
