### ISSUE TITLE
Clock hands not centered in clock widget

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/Akvo-Theme#406]
The arms of the clocks in the clock widget are off center. 
With the launch of the new homepage the clocks will only be visible on the regional pages I think, so quite buried. So please do homepage stuff before this one. 

<img width="1285" alt="Screenshot 2020-02-19 at 10 20 18" src="https://user-images.githubusercontent.com/5338081/74825241-80406d00-5301-11ea-87e5-c9e148a0d4dd.png">

Example: https://akvo.org/americas/

**Comment by Lindaleunissen** [comment]
Also just realised that the times are not correct. The Europe clock is an hour ahead.

**Comment by samvthom16** [comment]
@Lindaleunissen can you tell me the timings here in GMT for Europe?

**Comment by Lindaleunissen** [comment]
Brilliant thanks. 

Currently Europe is GMT+1 (CET)
on 29 March that will change to GMT+2 (CEST)

**Comment by samvthom16** [comment]
@Lindaleunissen can you confirm if this is working?

**Comment by Lindaleunissen** [comment]
Yes, works fine. Thank you!
