### ISSUE TITLE
Global color change

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#48]
Hi Sam :)

Can you perform a global color change over the styles:

Please change HEX #4e4a47 for #191919 everywhere.

This is a request from Linda :)

Ta

Chris

**Comment by designbychris** [comment]
Also can you change the class .bg-mid-grey, .bg-gray and .bg-light-gray to be the background hex color of #f2f2f2 as all these classes are going to call the same gray color, please can you comment out the original background colors for these just in case they want to be reverted later.

**Comment by samvthom16** [comment]
@designbychris I'll use variables within SASS for the first request. For the second request, you can override them in your css file.

**Comment by samvthom16** [comment]
@designbychris can you share the list of colors with hex values that we are using within the website. I will create a library of color variables in SASS for them.

**Comment by designbychris** [comment]
I think that this is correct :)

**Comment by designbychris** [comment]
I will probably get Linda to check this list of colours to make sure that she's happy.

**Comment by Lindaleunissen** [comment]
Hiya, Thanks for this. 

Red, blue, green and pink are correct. 
Dark black and mid black are correct too.

Where do we use black? And why do we have so many greys? Where do we use them?

**Comment by designbychris** [comment]
@Lindaleunissen they were being used on different sections of the site.. some of the greys were darker and some were lighter. 

e.g. on here : https://designbychris.co.uk/akvo/newsite/europe.php you will see the ligher grey being used in the background and here: https://designbychris.co.uk/akvo/newsite/about.php the darker. I also made a mid gray too.. but we can consolidate all grays to one gray if you would prefer.

**Comment by Lindaleunissen** [comment]
Is there any way we can  preset these colours in the different colour palettes in the builder?

**Comment by samvthom16** [comment]
List of predefined color palettes:
https://github.com/akvo/Akvo-Theme/issues/59

**Comment by samvthom16** [comment]
@designbychris
@Lindaleunissen  
There are other colors that are being used too. Are we going to continue using them like: 

new.scss - 
#eeeeee
#ededed
#ccc
#CACACA
#cacaca
#2c509a
#e2e3ea

inc/filters.scss - 
#f0f0f0
#797979
#f0f0f0
#aaa8a8

inc/modal.scss
#ddd

inc/navbar.scss
#222
#080808

@designbychris 
If we are going to use them, can we please list them in the library.scss?

**Comment by designbychris** [comment]
hmm not sure .. i'll have to review these colours with Linda ... 

I will go through these and consolidate them.. I do think that some of them are no longer needed. But I will need to find them and where they're used :)

**Comment by designbychris** [comment]
I have now assigned this to me for the moment while I go through these colours and find them all :)
