### ISSUE TITLE
Modal Form

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#49]
Hi Sam,

I have made some style amends to the form within the pop up in the footer. 

Can you do a few fixes for me?

On the select, I need it to have the label within the field as the first unselectable item, so its there but you can't choose it. Essentially giving the first option (if you select to put the labels within the fields from your other option, to give the first option being the label the: selected disabled on the <option> tag.

Does that make sense?

Thanks matey :)

Chris

**Comment by samvthom16** [comment]
@designbychris all the decisions on the forms are on hold until we know how we are handling for hubspot.

**Comment by designbychris** [comment]
Ok

**Comment by samvthom16** [comment]
@designbychris Why aren't we using gravity forms for this?

**Comment by designbychris** [comment]
We can be, I will make it into a Gravity Forms, form.
