### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by samvthom16** [akvo/Akvo-Theme#5]
- [x] Remove admin bar on frontend
- [x] Add logo to the theme folder
- [x] Replace content within the modals to be pulled dynamically from sidebars 
- [x] Fix page header widget as discussed in comment below
- [x] Clock widget - needs to be full width, with the grey background. Might be good to allow the admin to edit the titles etc. Though the clock function is found within the functions.php so i'm not sure how easy that will be - see the http://designbychris.co.uk/akvo/newsite/ at the bottom. These clocks have URLs on them for when they are clicked. Not sure if they will need to be edited dynamically, but they will need to have the links on them anyway. 
- [x] Logo slider widget - needs to be full width, with background colour option, needs to use CSS to override all logos to be greyscale (I can provide the CSS for this if needed or just set a class and I will update the CSS), also needs to allow for a custom title - this is about half way down on this page http://designbychris.co.uk/akvo/newsite/. 
- [x] Multi-stage form widget - As on this page https://designbychris.co.uk/akvo/newsite/europe.php the form for Drop us a message is over multiple stages with a load of fields. Would be good to allow this, as a custom widget with extra stages etc. So the user presses next after filling in each page. Would be good to allow the admin to add/remove pages and form fields within this widget.
- [x] Button widget - used all over, needs to have a couple of styles associated with it, one is .buttonwhite and the other is .buttonblack. They should use the CSS from within the style to make them as we have them set. An example can be found: https://designbychris.co.uk/akvo/newsite/about.php 
- [x] Organisation page update - Update the style of the organisation page widget to look more like this: https://designbychris.co.uk/akvo/newsite/organisations.php the filtering functionality needs to be retained. This also applies to anywhere else that this functionality is used, so it might be good for it to just select a custom post type and then display them (as the same functionality is used here: https://designbychris.co.uk/akvo/newsite/team.php ). Would be good to allow this functionality for the Stories too (see https://designbychris.co.uk/akvo/newsite/partner-stories.php ) I think what would be amazing, is that the filters are dynamically populated by the categories etc from the custom post type. Also would be good to allow the admin to either show or hide the filter, and select number of posts to display.
- [x] Map widget - again on the https://designbychris.co.uk/akvo/newsite/europe.php page, below the form, there is a map with an address. Ideally this widget would allow for multiple addresses and when you press on an address its a tab which will load a different tab with a different map on it, the more addresses the larger the map becomes, so if there is 3 or 4 of them the main map section will match the height of the boxes with the addresses in.
- [x] Partner page update - Update the style for the partner page, similar to the above with the organisation page. See updated page: https://designbychris.co.uk/akvo/newsite/partners.php
- [x] Testimonials widget 
- [x] Statistics widget 
- [x] CPT for advert

**Comment by designbychris** [comment]
I have added code to remove the admin bar and I have added the logo to the theme folder (though it was already in images/logos within the folder structure)

**Comment by designbychris** [comment]
Need to fix header image widget to force it full width within the code on the page.php all the content is within a container and is forcing the header image to stay within the container. Will need to force it to be wider/full width. See screenshot of the header.

![headerimage](https://user-images.githubusercontent.com/2072475/45145484-aa0ede00-b1b8-11e8-9734-d8a715d406fd.png)

Also suggest that we add some code around the dynamic title that it generates of the following code:

<div class="carousel-caption"><h1>_Title goes here_</h1></div>

Also from within the widget it forces a dropshadow around the font. Can we have that removed from the widget.

- [fix header widget as described above ]

**Comment by designbychris** [comment]
Am going to add the list of all widgets that need to be generated here

**Comment by samvthom16** [comment]
@designbychris my suggestion would be to to keep all the content within .container-fluid. The nested content that would need .container can be done through the page builder using a css class or something. An example would be https://akvo.org/stories/europe/working-towards-sustainable-hazelnut-production-turkey-utz/

**Comment by designbychris** [comment]
good plan on that @samvthom16 I will amend the container to be container-fluid and try from there.

**Comment by designbychris** [comment]
Have fixed the content in the header widget :) so thats ok now. I will update the git shortly

**Comment by designbychris** [comment]
Have added the widget areas to the modal windows

**Comment by samvthom16** [comment]
@designbychris as separate modules have been identified through shortcodes, their corresponding css can also be separated into individual scss files.

**Comment by designbychris** [comment]
ahh ok.. I will make them into individual scss files for you, where would you like them to be put in the file structure? Would you like me to make them go in a new folder within the CSS folder called Shorcodes within the CSS folder /css/shortcodes/ or within a folder called css within the templates folder like this: /lib/templates/css either I can do for you :)

**Comment by samvthom16** [comment]
Lets keep them inside the css folder

**Comment by designbychris** [comment]
ok no worries :) will aim to sort this for you today

**Comment by designbychris** [comment]
On the Multistage form.. It was discussed with Linda and we have decided to use Gravity Forms for this, as it allows for multistage forms without needing to code anything extra.

**Comment by samvthom16** [comment]
Issues from Laura:

- [ ] How do I add/remove and add URLs to the social media buttons in the footer? 

- [ ] 'Navigation' in the footer - could you please replace it with 'Explore resources'

- [ ] Privacy policy on the newsletter pop-up window needs to have the hyperlink underline. The font also seems to be different. Can you please have a look at the GDPR text on that form so that it has the same font size and styling?  

- [ ] Akvo Backstage blog: Can you change 'Things you may also like...' to 'You might also like...'

- [ ] The gravity form confirmation texts: can you please add the hyperlink underline to 'blog' and make the colour white? The font size of the whole sentence needs to be slightly smaller as well. The gravity form confirmation texts: can you please add the hyperlink underline to 'blog' and make the colour white? The font size of the whole sentence needs to be slightly smaller as well. ---> 'our blog' needs to be hyperlinked

- [ ] Form buttons on Improve and showcase your results: could you please make them the same as on Capture and understand data that matters

- [ ] The Disqus blog comments plugin on the single blog posts needs a bit more space above

**Comment by samvthom16** [comment]
Issues from Linda
1. Uploaded different videos on the homepage with 2 different embeds but they are both displaying the same video
2. Need translation for the hard coded text in the footer.
