### ISSUE TITLE
Map Tab

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#54]
I have added a new map_tab.php function as the old one didn't work.

I have put a new version in, and have added some new scss for map_tabs.. which I hope will work.

We will need to have a way to put a custom map in the body tab and then add multiple map locations on the fly, as some may only have 1 location, while others may have 5.

I've used SnazzyMaps for the time being.. though i'm sure that there will be a way to make the style we want on all google maps and and override of the pin to a custom pin without using SnazzyMaps :) hopefully the builder has something already :)

We might be able to use this elsewhere as a tab function.

Not sure what would be easier :)

**Comment by samvthom16** [comment]
@designbychris also share the visual reference of the same. Do note that all developments are dependent on the visual reference. If you have used SnazzyMaps then we will be using that. If we change to Google Maps only for the development, then again there is a difference in the development and the visual reference.

**Comment by designbychris** [comment]
I've built a test thing here: https://designbychris.co.uk/akvo/newsite/tabs/tabs3.html 

I think that it would be better if we didn't use Snazzy Maps. Because otherwise we'll need to do a stupid amount of work within Snazzy to make it work. We should be able to use the builders Map element for this, and just add a style:  

[maps-style-googlemap.txt](https://github.com/akvo/Akvo-Theme/files/2541965/maps-style-googlemap.txt)

and have a custom pin for the location.

Is that a good option by you?

**Comment by designbychris** [comment]
I have put a map into here: https://staging3.akvo.org/europe/ i'm just waiting for the API from Googlemaps to catch up. As I set a key in its just taking some time to catch up.

With my tabs function, are we going to be able to add this map to be within the actual tab content section without a problem?

I have some CSS with it which forces the map to be a height/width of 100%, as we have equal rows running on that section to make the map and the tabs the same size.

Hopefully this can all work :) I think it should :D

**Comment by samvthom16** [comment]
@designbychris As I mentioned earlier, I can't build on top of this widget. If this widget can't be used as it is then we need to find ways of embedding the Google maps directly into the tab.

**Comment by designbychris** [comment]
yeah thats perfect :) I think that we can just use the maps direct from Google TBH.. I'm pretty sure that I can implement a style from SnazzyMaps on a GoogleMap.. I just need to read up on it :) but if you can do the rest of the widget for the map and tabs then that would be great :) As it should all be there now :D

**Comment by designbychris** [comment]
@samvthom16 can you update Linda on where this is up to?
