### ISSUE TITLE
Keep a list of predefined colors for the color pallete

### ISSUE THREAD

**Issue by samvthom16** [akvo/Akvo-Theme#59]
https://siteorigin.com/thread/custom-iris-picker/

**Comment by samvthom16** [comment]
@designbychris 
Linda
I have updated the color palette to have these colors: 

#000000
#191919
#ffffff
#EA5547
#03AD8C
#404898
#E04D95

Could you review them for me if you need any changes?

**Comment by Lindaleunissen** [comment]
All good. Thanks for that, will make our lives a lot easier!
