### ISSUE TITLE
Our Partners filter

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#70]
Hi Sam :)

Can we add an "All" filter on the Our Partners filtering?

I'm not sure if this is something needed on all filters. Linda will need to answer that. But if we could add that in to the Our Partners filtering that would be great :)

Ta 
Chris

**Comment by samvthom16** [comment]
@designbychris The 'all' filtering can be enabled/disabled from the widget settings. Linda on the live had asked me to disable that for the partners because of duplication of data. If you want to enable, you can do it via the widget settings.

**Comment by designbychris** [comment]
I will let Linda know :) as she was asking.

**Comment by Lindaleunissen** [comment]
It should only be disabled on the organisations page. Everywhere else we need the all filter. But if I can set it myself, then it's not a problem. Thanks!
